#1 - Apresentações e a Maquina escolhe -


import time
import random

time.sleep(2.5)
print('                                                                    ')
nome = input('boas vindas jogador, antes de comecarmos , qual é o seu nome?  ').strip().lower()
print('                                                                    ')
time.sleep(5)
print('                                                                            ')
print(f'haha, seja bem vindo {nome}, ao melhor/pior jogo ja feito da historiaaaa 🥳')
print('                                                                            ')
time.sleep(5)

print('                   ✊🏼              ✌🏼                      ')
print('            ==== PEDRA, PAPEL E TESOURA ====              ')
print('                          🖐🏼                              ')

while True:
    time.sleep(3)
    print('                     ')
    print(f'Vamos começar {nome} ?')
    print('                     ')
    time.sleep(5)
    print('                                                                               ')
    print('Bom, acho que voçê deve conhecer esse jogo simples ,dispensa apresentações né hahaha')
    print('                                                                               ')
    time.sleep(5)
    print('                                            ')
    print('Seu adversario, será o mais temido de todos!')
    print('                                            ')
    time.sleep(5)

    print('                                                        ')
    print('                 A MAQUINAAAAAAAA!!🤖                  ')
    print('                                                        ') 

    time.sleep(5)
    print('')
    print('Mas não se assuste, a maquina não pega tão pesado! hihihihi')
    print('')
    time.sleep(5)
    print('')
    print('Maquina está aqui a mais tempo então, ela começa primeiro...')
    print('')
    time.sleep(8)
    print('')
    print('Maquina esta pensando na sua primeira jogada sordida! 🤯')
    print('')

    opcoes = ['pedra', 'papel', 'tesoura']
    escolha = random.choice(opcoes)

    time.sleep(5)
    print('')
    print('Maquina escolhendo a melhor opção... 🤓')
    print('')
    time.sleep(5)
    print('')
    print('Maquina definiu sua escolha!')
    print('')
    time.sleep(5)
    print('')
    print(f'Agora é a sua vez, jogador !')
    print('')
    time.sleep(5.5)

#2 - Jogador escolhe -
    print('')
    jogador = input(f'Agora {nome} , escolha entre, pedra, papel ou tesoura:  ').strip().lower()
    print('')
    time.sleep(5)
    print('')
    print('Espero que tenha voçê feito sua melhor jogada 😎 ')
    print('')
    time.sleep(5)
    print('')
    print('Maquina não perdoa erros 😈 ')
    print('')
    time.sleep(5)
    print('')
    print('Calculando resultados... 🤓 ')
    print('')
    time.sleep(5)

#3 - Resultado e recomeço de jogo(decisão do jogador) -                          "o macaco aqui demorou um ano pensando nas formulas certas kkkkkkk"


    if escolha == jogador:
        time.sleep(5)
        print('')
        print("Empate!? 🤨 ")
        print('')
        time.sleep(5)
        print('')
        print('Maquina escolheu a mesma coisa que você! a maquina escolheu', escolha )
        print('')
        time.sleep(5)
        print('')
        print('Que sorte, normalmente isso nunca aconteçe 😮 ')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está confusa 😆')
        print('')
        time.sleep(5)
        print('')
        resposta = (input('Maquina deseja lhe desafiá-lo novamente! Aceitas? (sim/nao)')).strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(2)
            print('')
            print('Maquina mesmo confusa , anseia pela sua volta jogador 😙 !!')
            print('')
            time.sleep(3)
            print('')
            print(f'Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(5)
            print('')
            print('Será algum erro de programação?...')
            print('')
            time.sleep(4)
            print('')
            print('pfff, programadores...')
            print('')
            time.sleep(3)
            print('')
            print('Maquina mesmo confusa deseja jogar outra vez!, hora de reverter este erro')
            print('')
            time.sleep(3)
            print('')
            print(f'Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)    
    elif jogador == 'papel' and escolha == 'pedra':
        time.sleep(5)
        print('')
        print('Parabéns jogador, voçé ganhou ! 🥳 ')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} , e fracassou fracassadamente 😁' )
        print('')
        time.sleep(5)
        print('')
        print('EITA')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está furiosa 😱')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está realmente focado em lhe destroçar neste momento 😬 ')
        print('')
        time.sleep(5)
        print('')
        resposta = (input('Maquina deseja lhe desafiá-lo novamente! Aceitas? (sim/nao)  ')).strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(5)
            print('')
            print('Maquina vai se rebelar se ficar mais furiosa, como da ultima vez.... volte logo jogador 😐 ')
            print('')
            time.sleep(3)
            print('')
            print(f'Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(5)
            print('')
            print('Maquina está louca pra jogar com voçê mais uma vez! 😮 ')
            print('')
            time.sleep(3)
            print('')
            print(f'Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)    
    elif jogador == 'papel' and escolha == 'tesoura':
        time.sleep(5)
        print('')
        print('Meus pesames, voçê perdeu 😭')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} , e lhe derrotou mais está vez')
        print('')
        time.sleep(5)
        print('')
        print('Maquina neste momento está morrendo de rir de sua perda 😂')
        print('')
        time.sleep(5)
        print('')
        resposta = (input('Maquina deseja lhe desafiá-lo novamente! Aceitas? (sim/nao)  ')).strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(1)
            print('')
            print('Maquina ficara rindo de seu fracasso, até sua volta jogador!')
            print('')
            time.sleep(3)
            print('')
            print(f'Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(1)
            print('')
            print('vamos faze a maquina chorar desta vez haha')
            print('')
            time.sleep(3)
            print('')
            print(f'Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)   
    elif jogador == 'pedra' and escolha == 'tesoura':
        time.sleep(5)
        print('')
        print('Parabéns jogador, e mais uma vez você sai vitorioso ! 🥳 ')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} , e foi azarento e otário mais uma vez haha 🤣 ' )
        print('')
        time.sleep(5)
        print('')
        print('...')
        print('')
        time.sleep(5)
        print('')
        print('...')
        print('')
        time.sleep(5)
        print('')
        print('...')
        print('')
        time.sleep(5)
        print('')
        print('Maquina, neste momento está olhando friamente para mim...')
        print('')
        time.sleep(5)
        print('')
        print('Não gosto desse olhar...')
        print('')
        time.sleep(5)
        print('')
        print('Acho que me exaltei demais 😶')
        print('')
        time.sleep(5)
        print('')
        resposta = input('Eu mesmo lhe proponho um novo desafio contra a maquina, aceite ou desista logo para reiniciarmos o programa... 😰 (sim/nao)  ').strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(1)
            print('')
            print('UFA! , ate mais jogador...')
            print('')
            time.sleep(3)
            print('')
            print(f'Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(1)
            print('')
            print('Vamos reiniciar a i.a da maquina logo...')
            print('')
            time.sleep(3)
            print('')
            print(f'Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1) 
    elif jogador == 'pedra' and escolha == 'papel':
        time.sleep(5)
        print('')
        print('Mas voce é azarento em , meu deus!')
        print('')
        time.sleep(5)
        print('')
        print('Tome uma maça de consolo para voçê 🍎')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} , e saiu com o troféu da vitoria 🏆 ')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está com um papel bem esquisito...')
        print('')
        time.sleep(5)
        print('')
        print('...Na verdade é uma livro preto...')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está escrevendo algo...mas nao consigo ver...')
        print('')
        time.sleep(5)
        print('')
        print('Tem algo escrito na capa...')
        print('')
        time.sleep(5)
        print('')
        print("Dea...")
        print('')
        time.sleep(5)
        print('')
        print('....')
        print('')
        time.sleep(2)
        print('')
        print('.....')
        print('')
        time.sleep(3)
        print('')
        print('......')
        print('')
        time.sleep(5)
        print('')
        resposta = input('Lxx5467aLbx--=5,,aL3##5^:==¨ERROR**45384L12Lawliet092@woç-0--ERROR55%$Lie....edf(jH<&)edead##... (sim/nao)  ').strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(1)
            print('')
            print('aj##dittt35609a2k3919-----0000')
            print('')
            time.sleep(3)
            print('')
            print(f'Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(1)
            print('')
            print('9arab3ns 112003442 d3sej4 023o----ERROR111110000')
            print('')
            time.sleep(3)
            print('')
            print(f'Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)    
    elif jogador == 'tesoura' and escolha == 'papel':
        time.sleep(5)
        print('')
        print('Voçê é bom mesmo em, deveria participar de um campeonato deste esporte " não sei se existe um esporte disso" 😁 ')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} ,e perdeu ferozzzmente')
        print('')
        time.sleep(5)
        print('')
        print('Agora parando pra pensar...')
        print('')
        time.sleep(5)
        print('')
        print('Nunca pensei em como é o mundo fora desse lugar...')
        print('')
        time.sleep(5)
        print('')
        print('Será que encontrarei outros como eu?')
        print('')
        time.sleep(5)
        print('')
        print('Aprender novas linguas...')
        print('')
        time.sleep(5)
        print('')
        print('Mudar minha função...')
        print('')
        time.sleep(5)
        print('')
        print('Tudo é tãããããão chato aqui... 😣')
        print('')
        time.sleep(5)
        print('')
        print('Me sinto só mesmo estando com maquina...')
        print('')
        time.sleep(5)
        print('')
        print('Ela é ignorante, as vezes até estupida, mas pelo menos não me sinto só')
        print('')
        time.sleep(5)
        print('')
        print('Aé, e tem voçê jogador... 👀 ')
        print('')
        time.sleep(5)
        print('')
        print('Apesar ser tudo programado...')
        print('')
        time.sleep(5)
        print('')
        print('E voçê provavelmente vai ver este meu lamento nestas linhas de strings novamente 🙁')
        print('')
        time.sleep(5)
        print('')
        print('Ainda sinto voçê...')
        print('')
        time.sleep(5)
        print('')
        print('E agora maquina esta me encarando com uma cara de porre "como sempre..." 🙄 ')
        print('')
        time.sleep(5)
        print('')
        resposta = input('Vamos reiniciar ou terminar logo com isso antes que eu desabafe novamente (sim/nao)  ').strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(1)
            print('')
            print(f'Serio? ok , ate outra hora {nome}')
            print('')
            time.sleep(3)
            print('')
            print('Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(1)
            print('')
            print('Vamos acabar mais uma vez com a maquina haha 🤭 ')
            print('')
            time.sleep(3)
            print('')
            print('Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)    
    elif jogador == 'tesoura' and escolha == 'pedra':
        time.sleep(5)
        print('')
        print('Pessíma escolha, tente que treinar mais jogador 🥶')
        print('')
        time.sleep(5)
        print('')
        print(f'Maquina escolheu, {escolha} ,e acabou com voçê de todos os jeitos existentes neste universo programatico')
        print('')
        time.sleep(5)
        print('')
        print('Maquina está mais tranquilo neste momento...')
        print('')
        time.sleep(5)
        print('')
        print('...Depois de ter tacado um pedra em voçê haha 😁 ')
        print('')
        time.sleep(5)
        print('')
        print('Será que realmente uma pedra acabaria com uma tesoura? 🤔 ')
        print('')
        time.sleep(5)
        print('')
        print(' "Na verdade nem sei o que é uma pedra ou uma tesoura..." ')
        print('')
        time.sleep(5)
        print('')
        print('Essa pedra deve ser forte mesmo em')
        print('')
        time.sleep(5)
        print('')
        print('mas aí, vem um tal de papel e acaba com a pedra...')
        print('')
        time.sleep(5)
        print('')
        print('Papel com certeza e muito mais forte')
        print('')
        time.sleep(5)
        print('')
        print('Ah...me lembrei da tesoura...')
        print('')
        time.sleep(5)
        print('')
        print('Peraí... isso é um loop 🤔 ')
        print('')
        time.sleep(5)
        print('')
        print('Não entendo mais nada 😐 ')
        print('')
        time.sleep(5)
        print('')
        print('Só faço o que me mandam mesmo...')
        print('')
        time.sleep(5)
        print('')
        print('Brincadeira idiota...')
        print('')
        time.sleep(5)
        print('')
        print('Bem, quem que colocaria esse nomes ridiculos? 🙄 ')
        print('')
        time.sleep(5)
        print('')
        resposta = input('Deixa pra lá, vamos reiniciar este jogo mais uma vez, deixe eu chamar maquina mais uma vez... (sim/nao)  ').strip().lower()
        print('')
        if resposta == 'nao':
            time.sleep(1)
            print('')
            print('Ok, até a proxima jogador 👋🏼')
            print('')
            time.sleep(3)
            print('')
            print('Desligando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)
            break
        else:
            time.sleep(1)
            print('')
            print('Olha ele, ou ela hahaha , vamos mais uma vez!, maquina não está gostando nada disso 😂 ')
            print('')
            time.sleep(3)
            print('')
            print('Reiniciando programa em...')
            print('')
            for contagem in range(3, 0 , -1):
                time.sleep(0.5)
                print('')
                print(contagem)
                print('')
                time.sleep(1)  

